### ISSUE TITLE
License

### ISSUE THREAD

**Issue by afs2015** [alexburr/Estimator#3]
Just was wondering @alexburr if you wanted a particular license attached to the project? http://choosealicense.com

If so, i'm happy to throw it in as a pull request with a lincense.md file and update the readme to reflect that.

**Comment by alexburr** [comment]
I don't have a particular preference, I just made it to teach myself React, since I had jQuery-based version I was using earlier (http://www.alexburr.com/static/music/songLength/index.html)
I guess MIT or GNU?

**Comment by afs2015** [comment]
Cool, i'll go with MIT and mark this issue as closed. Feel free to open if it you decide to change the license.
